### PR TITLE
request to merge with develop branch

### PR DESCRIPTION
**Pull request by mohamednaser**
## Done Work

- [x] List predefined books .
- [x] Add your favorite book.
- [x] delete any book.
- [x] change read status for any book.
- [x] do any action in realtime you don't need to refresh the page.

### CODE REVIEW

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required 🔍 👀


Hi @mohamednaser! Hi @Salvador-ON! 👋 

Great job btw! 😄 
It's really great that you were able to use firebase.
However, but you bypassed some of the key requirements being tested for this project, the object was to use firebase in tandem with what you've already created in previous steps. It was meant to be a way of storing (alternate to `localStorage`) while still keeping the functionalities of previous steps.
In fact, the firebase step was optional, the others weren't. Please consider using firebase in tandem with other requirements.

Some of these include
- Have an array store all instances of `Book` (see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/book_array_requirement.png))
- Have `Book` object (see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/book_array_requirement.png))


Please take a look at the instructions in Odin again and follow them 🙏 👍 : https://www.theodinproject.com/courses/javascript/lessons/library


***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by mohamednaser** [comment]
hello @mcrd25 ,

we already use firebase to manage all books object state (add, remove, update ) so why we need to recode these functions with a local state ?!  

I think we can choose which storage we will use local storage or firebase and we decided to use firebase instead of using local storage and we don't know actually where is the problem

**Comment by Salvador-ON** [comment]
We modify our project to Have an array (mylibrary) store all instances of Book

in our case after the optional step of using firebase we need to modify the books object to be managed by firebase

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap:  

You can merge it :+1: 
Good continuation :handshake: 

Mael FOSSO

**Comment by mcrd25** [comment]
> hello @mcrd25 ,
> 
> we already use firebase to manage all books object state (add, remove, update ) so why we need to recode these functions with a local state ?!
> 
> I think we can choose which storage we will use local storage or firebase and we decided to use firebase instead of using local storage and we don't know actually where is the problem

Hi Guys,  I never said to delete firebase 😅 . Please read carefully I said you were to use either localStorage or Firebase but this was optional the key components were already mentioned in the project which you were missing. Hope you understand. You got te approval though, so yay!

**Pull request merged**
